version: "3.8"

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

  web:
    build: backend/
    volumes:
      - ./backend/:/backend/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
