[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--spec --cov=app --cov-report html"

[tool.black]
target-version = ["py39"]
line-length = 89
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.flake8]
ignore = ["E203", "E266", "E501", "W503", "F403", "F401"]
max-line-length = 89
max-complexity = 18
select = ["B","C","E","F","W","T4","B9"]
